/**
 * Salary-guide PDF lead-magnet availability flag (audit P0 #6 → P1 #4).
 *
 * P0 #6 gated the whole email-capture funnel on this flag because the PDF
 * the funnel promised was a dead storage object. P1 #4 authored the real
 * deliverable: public/downloads/np-salary-guide-2026.pdf, generated by
 * scripts/generate-salary-pdf.ts (STAT_SOURCES national figures + the
 * published /salary-guide market bands + EXACT live posting counts — it
 * deliberately freezes no per-state wage aggregate, see the long note
 * above fetchLiveInventory in the generator) and served from this app
 * behind brand.assets.salaryGuidePdf. The flag is now ON.
 *
 * Every surface still honors the flag, so it remains the single kill
 * switch if the deliverable ever goes stale or dead again:
 *
 *   - app/api/salary-guide/route.ts refuses (503) before capturing the
 *     lead or sending the email;
 *   - app/salary-guide/page.tsx hides the "Download Free PDF Guide" card;
 *   - components/ResourceDownloadGate.tsx swaps the email-capture form
 *     for a plain link to the live /salary-guide content.
 *
 * Flip OFF if the PDF is removed or its figures are found stale; flip
 * back ON only after regenerating via scripts/generate-salary-pdf.ts
 * (tests/regressions/p1-salary-pdf-deliverable.test.ts asserts the file
 * behind brand.assets.salaryGuidePdf actually exists while this is true).
 *
 * This is a plain constant (no server-only imports) so both server
 * components and client components can share the single source of truth.
 * It lives beside the API route that delivers the PDF.
 */
import { brand } from '@/config/brand';

export const SALARY_GUIDE_PDF_AVAILABLE = true;

/**
 * Edition year of the PDF that is actually on disk, parsed from the
 * published asset filename (np-salary-guide-2026.pdf → '2026').
 *
 * Why derived and not `new Date().getFullYear()`: the artifact is a
 * frozen file. A clock-derived label advertises a "2027 salary guide" on
 * 1 January while the funnel still hands over the 2026 PDF — the same
 * description-does-not-match-the-deliverable failure P0 #6 gated. Every
 * surface that names the edition (hub page card, /resources card, the
 * delivery email, the PDF's own cover) reads this constant, so the label
 * can only change when a newly named file is actually generated.
 *
 * tests/regressions/p1-salary-pdf-copy-truth.test.ts guards both halves:
 * that this matches the file on disk, and that no surface re-introduces
 * a clock-derived edition year.
 */
export const SALARY_GUIDE_EDITION_YEAR: string = (() => {
    const filename = new URL(brand.assets.salaryGuidePdf).pathname.split('/').pop() ?? '';
    const match = filename.match(/(20\d{2})/);
    if (!match) {
        throw new Error(
            `brand.assets.salaryGuidePdf ("${brand.assets.salaryGuidePdf}") carries no 20xx edition year in its ` +
            `filename. Name the artifact <slug>-<year>.pdf so every surface can label the edition it actually serves.`,
        );
    }
    return match[1];
})();
