'use client';

import { useState, useSyncExternalStore } from 'react';
import Link from 'next/link';
import { Download, CheckCircle, Loader2, Mail, ArrowRight } from 'lucide-react';
import { SALARY_GUIDE_PDF_AVAILABLE } from '@/app/api/salary-guide/pdf-availability';

interface ResourceDownloadGateProps {
    resourceUrl: string;
    resourceTitle: string;
}

const STORAGE_KEY = 'resource_download_unlocked';

// localStorage read via useSyncExternalStore instead of a setState-in-effect
// (react-hooks/set-state-in-effect): server snapshot is false, client snapshot
// reads storage after hydration — same behavior, no cascading render.
const subscribeNoop = () => () => {};
const getUnlockedSnapshot = () => {
    try {
        return localStorage.getItem(STORAGE_KEY) === 'true';
    } catch {
        return false;
    }
};
const getUnlockedServerSnapshot = () => false;

export default function ResourceDownloadGate({ resourceUrl, resourceTitle }: ResourceDownloadGateProps) {
    const storedUnlocked = useSyncExternalStore(subscribeNoop, getUnlockedSnapshot, getUnlockedServerSnapshot);
    const [justUnlocked, setJustUnlocked] = useState(false);
    const unlocked = storedUnlocked || justUnlocked;
    const [email, setEmail] = useState('');
    const [status, setStatus] = useState<'idle' | 'loading' | 'done'>('idle');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        const trimmed = email.trim();
        if (!trimmed || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) return;

        setStatus('loading');
        try {
            await fetch('/api/newsletter', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ email: trimmed, source: 'resource_download' }),
            });
        } catch { /* silent */ }
        try {
            localStorage.setItem(STORAGE_KEY, 'true');
        } catch { /* storage unavailable — session-only unlock */ }
        setJustUnlocked(true);
        setStatus('done');
        // Auto-trigger download
        window.open(resourceUrl, '_blank');
    };

    // Audit P0 #6 / P1 #4: the PDF deliverable is real now
    // (public/downloads, generated by scripts/generate-salary-pdf.ts), so
    // the flag is ON and the email-capture gate below is live. This branch
    // stays as the kill switch: if the PDF ever goes dead again, flipping
    // the flag in app/api/salary-guide/pdf-availability.ts swaps capture
    // back out for a plain link to the live /salary-guide content.
    if (!SALARY_GUIDE_PDF_AVAILABLE) {
        return (
            <Link
                href="/salary-guide"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-lg font-semibold text-white transition-colors"
                style={{ background: 'linear-gradient(135deg, #F472B6, #DB2777)' }}
            >
                View the Full Salary Guide
                <ArrowRight size={18} />
            </Link>
        );
    }

    if (unlocked) {
        return (
            <a
                href={resourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-lg font-semibold text-white transition-colors"
                style={{ background: 'linear-gradient(135deg, #F472B6, #DB2777)' }}
            >
                <Download size={18} />
                Download {resourceTitle}
            </a>
        );
    }

    return (
        <div
            className="rounded-xl p-6 max-w-md"
            style={{
                background: 'linear-gradient(135deg, rgba(244,114,182,0.08), rgba(219,39,119,0.04))',
                border: '1px solid rgba(244,114,182,0.2)',
            }}
        >
            <div className="flex items-center gap-2 mb-3">
                <Mail size={20} style={{ color: '#DB2777' }} />
                <h4 className="font-semibold" style={{ color: 'var(--text-primary)' }}>Get free access</h4>
            </div>
            <p className="text-sm text-gray-600 mb-4">
                Enter your email to download the {resourceTitle}. You&apos;ll also receive career tips & job market updates.
            </p>
            <form onSubmit={handleSubmit} className="flex gap-2">
                <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="you@example.com"
                    required
                    className="flex-1 px-3 py-2.5 rounded-lg text-sm border border-gray-300 focus:ring-2 focus:ring-pink-600 focus:border-pink-600 outline-none"
                />
                <button
                    type="submit"
                    disabled={status === 'loading'}
                    className="px-4 py-2.5 rounded-lg text-sm font-semibold text-white disabled:opacity-50 flex items-center gap-1"
                    style={{ background: 'linear-gradient(135deg, #F472B6, #DB2777)' }}
                >
                    {status === 'loading' ? (
                        <Loader2 size={16} className="animate-spin" />
                    ) : status === 'done' ? (
                        <><CheckCircle size={16} /> Done</>
                    ) : (
                        <><Download size={16} /> Get PDF</>
                    )}
                </button>
            </form>
        </div>
    );
}
