/**
 * Indexing audit CQ-12, rendering side: with brand.editorial.author and
 * .reviewer filled (mocked here with test identities, never shipped), the
 * visible byline names both people and the schema fields default to the same
 * objects; the generated license-guide byline still names nobody.
 */
import { describe, it, expect, vi } from 'vitest';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

vi.mock('@/config/brand', async (importOriginal) => {
    const actual = await importOriginal<typeof import('@/config/brand')>();
    return {
        ...actual,
        brand: {
            ...actual.brand,
            editorial: {
                ...actual.brand.editorial,
                author: { name: 'Test Author', credentials: 'MSN, APRN', title: 'Editor', profileUrl: '/about#editor' },
                reviewer: { name: 'Test Reviewer', credentials: 'DNP, APRN, FNP-BC', profileUrl: 'https://example.com/reviewer' },
            },
        },
    };
});

const { default: EditorialByline, editorialSchemaFields } = await import('@/components/EditorialByline');

describe('byline with a named author and reviewer', () => {
    it('names the author, links the bio, and names the reviewer', () => {
        const html = renderToStaticMarkup(React.createElement(EditorialByline));
        expect(html).toContain('Written by');
        expect(html).toContain('<a style="color:#BE185D;text-decoration:underline" href="/about#editor"><strong style="color:#1A2E35">Test Author, MSN, APRN</strong></a>');
        expect(html).toContain(', Editor');
        expect(html).toContain('Clinically reviewed by');
        expect(html).toContain('Test Reviewer, DNP, APRN, FNP-BC');
        expect(html).toContain('href="https://example.com/reviewer"');
        expect(html).not.toContain('editorial team');
    });

    it('schema fields default to the same config objects', () => {
        const fields = editorialSchemaFields() as Record<string, Record<string, unknown>>;
        expect(fields.author).toMatchObject({ '@type': 'Person', name: 'Test Author', url: 'https://nphiring.com/about#editor' });
        expect(fields.reviewedBy).toMatchObject({ '@type': 'Person', name: 'Test Reviewer' });
    });

    it('a generated license guide still names nobody', () => {
        const html = renderToStaticMarkup(React.createElement(EditorialByline, { generated: true }));
        expect(html).toContain('Generated by');
        expect(html).not.toContain('Test Author');
        expect(html).not.toContain('Test Reviewer');
        expect(html).not.toContain('Clinically reviewed by');
    });
});
