/**
 * Indexing audit CQ-12: authorship renders as a named schema.org Person
 * `author` and a Person `reviewedBy` the moment the owner fills
 * brand.editorial.author and .reviewer (config/brand.ts), without anyone
 * being invented in the meantime.
 *
 * Pins:
 *   1. Both config fields default to null, and the byline then credits the
 *      editorial team and emits no Person.
 *   2. editorialSchemaFields() builds the Person records from the config
 *      objects, with nothing invented for fields left out.
 *   3. Every consumer spreads it AFTER its Organization author, so a filled
 *      author replaces the Organization; the blog post page never spreads it
 *      on a generated license guide.
 *   (Rendering with filled config: editorial-byline-named.test.ts.)
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { brand, type EditorialAuthor, type EditorialReviewer } from '@/config/brand';
import EditorialByline, { authorDisplayName, editorialSchemaFields } from '@/components/EditorialByline';

const ROOT = process.cwd();
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

const AUTHOR: EditorialAuthor = {
    name: 'Test Author',
    credentials: 'MSN, APRN',
    title: 'Editor',
    profileUrl: '/about#editor',
};
const REVIEWER: EditorialReviewer = {
    name: 'Test Reviewer',
    credentials: 'DNP, APRN, FNP-BC',
    title: 'Clinical Reviewer',
    profileUrl: 'https://example.com/reviewer',
    npi: '1234567890',
};

describe('config defaults: nobody is invented', () => {
    it('author and reviewer both default to null', () => {
        expect(brand.editorial.author).toBeNull();
        expect(brand.editorial.reviewer).toBeNull();
    });

    it('with both null, the byline credits the editorial team and schema adds nothing', () => {
        const html = renderToStaticMarkup(React.createElement(EditorialByline));
        expect(html).toContain(`Written and maintained by the ${brand.name} editorial team`);
        expect(html).not.toContain('Written by ');
        expect(html).not.toContain('Clinically reviewed by');
        expect(html).toContain(`href="${brand.editorial.policyPath}"`);
        expect(editorialSchemaFields()).toEqual({});
    });

    it('the generated byline disclaims authorship and review', () => {
        const html = renderToStaticMarkup(React.createElement(EditorialByline, { generated: true }));
        expect(html).toContain('This page was not individually');
        expect(html).not.toContain('editorial team');
    });

    it('config/brand.ts documents where the owner fills the two fields', () => {
        const src = read('config/brand.ts');
        expect(src).toContain('OWNER FILLS THESE TWO FIELDS');
        expect(src).toContain('author: null as EditorialAuthor | null,');
        expect(src).toContain('reviewer: null as EditorialReviewer | null,');
    });
});

describe('editorialSchemaFields()', () => {
    it('emits a Person author from the author config, with an absolute bio URL', () => {
        expect(editorialSchemaFields(null, AUTHOR)).toEqual({
            author: {
                '@type': 'Person',
                name: 'Test Author',
                honorificSuffix: 'MSN, APRN',
                jobTitle: 'Editor',
                url: `${brand.baseUrl}/about#editor`,
            },
        });
    });

    it('invents nothing for an author with only a name', () => {
        expect(editorialSchemaFields(null, { name: 'Test Author' })).toEqual({
            author: { '@type': 'Person', name: 'Test Author' },
        });
        expect(authorDisplayName({ name: 'Test Author' })).toBe('Test Author');
        expect(authorDisplayName(AUTHOR)).toBe('Test Author, MSN, APRN');
    });

    it('emits author and reviewedBy together', () => {
        const fields = editorialSchemaFields(REVIEWER, AUTHOR) as Record<string, Record<string, unknown>>;
        expect(fields.author).toMatchObject({ '@type': 'Person', name: 'Test Author' });
        expect(fields.reviewedBy).toMatchObject({
            '@type': 'Person',
            name: 'Test Reviewer',
            url: 'https://example.com/reviewer',
            identifier: { '@type': 'PropertyValue', propertyID: 'NPI', value: '1234567890' },
        });
    });

    it('replaces the Organization author when spread after it', () => {
        const article = { author: { '@type': 'Organization', name: brand.name }, ...editorialSchemaFields(null, AUTHOR) };
        expect(article.author).toMatchObject({ '@type': 'Person', name: 'Test Author' });
        const unfilled = { author: { '@type': 'Organization', name: brand.name }, ...editorialSchemaFields(null, null) };
        expect(unfilled.author).toEqual({ '@type': 'Organization', name: brand.name });
    });
});

describe('every editorial surface spreads the fields after its Organization author', () => {
    /**
     * The audit's CQ-12 fix (and plan fixSoon 13) covers the editorial posts,
     * the resource guides and the salary hub. The salary hub entry passes once
     * the app/salary-guide/page.tsx handoff lands.
     */
    const CONSUMERS: Array<[string, string]> = [
        ['app/resources/1099-vs-w2/page.tsx', '...editorialSchemaFields(),'],
        ['app/resources/fpa-guide/page.tsx', '...editorialSchemaFields(),'],
        ['app/resources/private-practice-guide/page.tsx', '...editorialSchemaFields(),'],
        ['app/scope-of-practice/page.tsx', '...editorialSchemaFields(),'],
        ['app/salary-guide/page.tsx', '...editorialSchemaFields(),'],
        ['app/blog/[slug]/page.tsx', '...namedPeople,'],
    ];

    /** An `author` key, bare or quoted either way ('author' in most files, "author" on /salary-guide). */
    const AUTHOR_KEY = /["']?author["']?: \{/g;
    const ORGANIZATION_AUTHOR = /["']?author["']?: \{\s*["']@type["']: ["']Organization/;

    it.each(CONSUMERS)('%s', (file, spread) => {
        const src = read(file);
        const at = src.indexOf(spread);
        expect(at, `${file}: no spread`).toBeGreaterThan(-1);
        // The nearest author key above the spread is the Organization one.
        const before = src.slice(0, at);
        const authorAt = Math.max(-1, ...[...before.matchAll(AUTHOR_KEY)].map((m) => m.index ?? -1));
        expect(authorAt, `${file}: spread must follow the Organization author`).toBeGreaterThan(-1);
        expect(before.slice(authorAt, authorAt + 60)).toMatch(ORGANIZATION_AUTHOR);
        expect(src).toContain('<EditorialByline');
    });

    it('the author key matcher reads both quoting styles (guards the guard)', () => {
        const single = "author: { '@type': 'Organization', name: brand.name },\n...editorialSchemaFields(),";
        const double = '"author": { "@type": "Organization", "name": brand.name },\n...editorialSchemaFields(),';
        for (const sample of [single, double]) {
            const hits = [...sample.matchAll(AUTHOR_KEY)];
            expect(hits).toHaveLength(1);
            expect(sample.slice(hits[0].index)).toMatch(ORGANIZATION_AUTHOR);
        }
        expect("author: { '@type': 'Person', name: 'x' }").not.toMatch(ORGANIZATION_AUTHOR);
    });

    it('the blog post page never attaches named people to a generated license guide', () => {
        const src = read('app/blog/[slug]/page.tsx');
        expect(src).toContain('const namedPeople = licenseSlugMatch ? {} : editorialSchemaFields();');
    });
});
