/**
 * Regression guards — content/SEO audit P1 #4 (salary-pdf package).
 *
 * The salary-guide email funnel's lead magnet is now a real, locally
 * hosted PDF: public/downloads/np-salary-guide-2026.pdf, generated by
 * scripts/generate-salary-pdf.ts and served behind
 * brand.assets.salaryGuidePdf. These guards keep the funnel honest:
 *
 *   1. While SALARY_GUIDE_PDF_AVAILABLE is true, the file behind
 *      brand.assets.salaryGuidePdf must exist in public/ and be a real
 *      PDF — the P0 #6 "email capture for a dead link" failure mode must
 *      never silently return.
 *   2. The generator's figures must trace to lib/stats-sources.ts /
 *      live DB aggregation / config/niche/salary.ts — never hardcoded
 *      national numbers.
 *   3. The generator must NOT freeze a per-state wage aggregate into the
 *      PDF. Validating the first cut against the live database showed
 *      that aggregate mixes annualized contract/locum hourly rates
 *      ($350/hr × 2,080 = $728,000) and physician postings in with W-2
 *      salaries, producing state "averages" of $250k–$380k against the
 *      federal national median on page 1. A daily-updated web table can
 *      carry that caveat; a PDF that gets cited for years cannot. The
 *      PDF prints exact live COUNTS plus the published validation bands
 *      and links to the live table instead. See the long note above
 *      fetchLiveInventory in the generator.
 *   4. The market-band copy in the generator MIRRORS the published
 *      /salary-guide page (the sanctioned home of that copy). If the
 *      page's bands change, this drift guard fails → edit the page,
 *      sync the generator, regenerate the PDF.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import { brand } from '@/config/brand';
import { SALARY_GUIDE_PDF_AVAILABLE } from '@/app/api/salary-guide/pdf-availability';

const ROOT = process.cwd();
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

const GENERATOR = 'scripts/generate-salary-pdf.ts';
const HUB_PAGE = 'app/salary-guide/page.tsx';

const pdfLocalPath = path.join(
    ROOT,
    'public',
    new URL(brand.assets.salaryGuidePdf).pathname.replace(/^\//, ''),
);

describe('P1 #4 — the PDF deliverable actually exists while the funnel is on', () => {
    it('brand.assets.salaryGuidePdf is served from this app, not a storage bucket', () => {
        const url = new URL(brand.assets.salaryGuidePdf);
        expect(url.origin).toBe(brand.baseUrl);
        expect(url.pathname).toMatch(/^\/downloads\/.+\.pdf$/);
    });

    it('the file behind the URL exists in public/ and is a non-trivial PDF', () => {
        // If this fails, either regenerate (scripts/generate-salary-pdf.ts)
        // or flip SALARY_GUIDE_PDF_AVAILABLE off — never ship the funnel
        // pointing at a dead file.
        expect(SALARY_GUIDE_PDF_AVAILABLE).toBe(true);
        expect(fs.existsSync(pdfLocalPath)).toBe(true);

        const buf = fs.readFileSync(pdfLocalPath);
        expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
        expect(buf.length).toBeGreaterThan(50_000); // multi-page, embedded art
    });
});

describe('P1 #4 — generator figures trace to sanctioned sources only', () => {
    const src = read(GENERATOR);

    it('national figures derive from lib/stats-sources.ts', () => {
        expect(src).toContain("from '@/lib/stats-sources'");
        expect(src).toContain('STAT_SOURCES.averageSalary');
        expect(src).toContain('STAT_SOURCES.blsGrowth2032');
        expect(src).toContain('STAT_SOURCES.fullPracticeStates');
        expect(src).toContain('STAT_SOURCES.hrsaShortagePopulation');
        // The OEWS median must never be re-hardcoded in the generator.
        expect(src).not.toContain('129,210');
        expect(src).not.toContain('129210');
    });

    it('live posting counts use the hub page’s disclosed-salary filter, so they agree', () => {
        const hub = read(HUB_PAGE);
        const disclosedSalaryWhere = 'isPublished: true, normalizedMinSalary: { not: null }';
        expect(src).toContain(disclosedSalaryWhere);
        expect(hub).toContain(disclosedSalaryWhere);
    });

    it('prints only exact COUNTS from postings — never a derived per-state wage', () => {
        // The distortion this guards against: annualized contract/locum
        // hourly rates and physician postings inflating a per-state mean.
        // Counting rows is safe; averaging their salaries here is not.
        expect(src).toContain('_count: { id: true }');
        expect(src).not.toContain('_avg:');
        expect(src).not.toContain('_min:');
        expect(src).not.toContain('_max:');
        // No per-state salary ranking survives into the document.
        expect(src).not.toMatch(/avgSalary/);
        expect(src).not.toMatch(/Avg\. Posted Salary/);
    });

    it('explains in the document why no state wage table is frozen in', () => {
        expect(src).toContain('Why this guide does not print a state-by-state wage table');
        // …and routes the reader to the live table instead of a snapshot.
        expect(src).toMatch(/updates daily and is\s+free/);
    });

    it('salary bands come from config/niche/salary.ts and are labeled as validation bands', () => {
        expect(src).toContain("from '@/config/niche/salary'");
        expect(src).toContain('salaryConfig.normalizer');
        expect(src).toContain('Salary-Validation Bands');
        // Contract hourly must be presented as hourly, with the annualization trap called out.
        expect(src).toContain('do not annualize it to compare against a W-2 offer');
        expect(src).toContain('salaryConfig.hoursPerYear');
    });

    it('handles an unreachable database without inventing counts', () => {
        expect(src).toMatch(/Live inventory counts were unavailable when this edition was generated/);
    });

    it('styling derives from the email design system, and copy from brand tokens', () => {
        expect(src).toContain("from '@/lib/email-templates-v2'");
        expect(src).toContain('brand.niche.short');
        expect(src).toContain('brand.domain');
    });
});

describe('P1 #4 — generator copy mirrors the published /salary-guide page (drift guard)', () => {
    const generatorSrc = read(GENERATOR);
    const hubSrc = read(HUB_PAGE);

    // Raw source literals (template-literal syntax included) that must be
    // byte-identical in both files. Editing the page without syncing the
    // generator (and regenerating the PDF) fails here on purpose.
    const mirroredLiterals = [
        // Experience bands
        "{ exp: 'New Grad (0-1 yr)', range: '$95,000 - $115,000', roles: `Staff ${brand.niche.short}, Outpatient Clinic` }",
        "{ exp: 'Early Career (1-3 yrs)', range: '$110,000 - $130,000', roles: `Staff ${brand.niche.short}, Telehealth Provider` }",
        "{ exp: 'Mid-Career (3-7 yrs)', range: '$125,000 - $150,000', roles: `Senior ${brand.niche.short}, Team Lead` }",
        "{ exp: 'Experienced (7-15 yrs)', range: '$150,000 - $180,000', roles: 'Clinical Director, Supervisor' }",
        "{ exp: 'Expert (15+ yrs)', range: '$180,000 - $250,000+', roles: 'Director, Consultant, Private Practice' }",
        // Setting ranges
        "setting: 'Private Practice (Owner)', range: '$180,000 - $300,000+', notes: 'Highest earning potential, requires business skills'",
        "setting: 'Travel / Locum Tenens', range: '$150,000 - $250,000', notes: 'Includes housing, travel, higher hourly rates'",
        "setting: 'Telehealth / Remote', range: '$130,000 - $180,000', notes: 'Growing rapidly, flexible schedules'",
        "setting: 'Outpatient Clinic', range: '$120,000 - $160,000', notes: 'Most common setting, steady patient load'",
        "setting: 'Hospital / Inpatient', range: '$115,000 - $150,000', notes: 'Often includes shift differentials, benefits'",
        "setting: 'Community Health (FQHC)', range: '$100,000 - $130,000', notes: 'May qualify for loan forgiveness programs'",
        // Specialty premiums — prefix only (no closing brace): the hub rows
        // additionally carry a `slug` link field (P1 #7) the PDF omits.
        "specialty: 'Acute Care / Hospitalist', premium: '+10-20%', notes: 'AGACNP certification, hospital demand'",
        "specialty: 'Psychiatric-Mental Health', premium: '+10-20%', notes: 'PMHNP-BC certification, provider shortage'",
        "specialty: 'Emergency / Urgent Care', premium: '+10-20%', notes: 'Dynamic environment, flexible scheduling'",
        "specialty: 'Dermatology / Aesthetics', premium: '+10-25%', notes: 'Procedure-driven, cash-pay revenue'",
        "specialty: 'Gerontology / Palliative', premium: '+5-10%', notes: 'Growing aging population'",
        "specialty: 'Private Practice (Owner)', premium: '+20-40%', notes: 'Higher risk, no benefits'",
        "specialty: 'Rural / Underserved', premium: '+10-15%', notes: 'Often includes loan repayment'",
        // Negotiation factor-card copy
        "desc: 'States with higher cost of living and greater demand (CA, NY, MA) typically offer 20-40% higher salaries than rural areas.'",
        "desc: `Entry-level ${brand.niche.short}s start around $95-115k. With 5+ years experience, salaries can reach $150-180k or more.`",
        "desc: 'Private practice and telehealth positions often pay more than hospital or community health settings.'",
        "desc: `1099 contractors and travel ${brand.niche.short}s often earn 20-50% more than W2 employees, though without traditional benefits.`",
        "desc: 'Subspecialties like acute care, emergency, psychiatric-mental health, or dermatology can command premium pay (+10-25%).'",
        "desc: `${brand.niche.short}s who negotiate can often secure 5-15% higher starting salaries plus signing bonuses ($5,000-$30,000).`",
    ];

    for (const literal of mirroredLiterals) {
        it(`mirrors: ${literal.slice(0, 60)}…`, () => {
            expect(hubSrc).toContain(literal);
            expect(generatorSrc).toContain(literal);
        });
    }

    it('FPA premium copy matches the page (12-15% more)', () => {
        expect(hubSrc).toContain('12-15% more');
        expect(generatorSrc).toContain('12-15% more');
    });
});
