/**
 * B44: drift guard between the canonical city dataset (lib/pseo/city-data/
 * cities.ts) and the edge-runtime allowlist the middleware 410s against
 * (lib/pseo/city-data/city-slugs-edge.ts).
 *
 * city-slugs-edge.ts is regenerated by hand (see its header). If cities.ts
 * is regenerated with new cities and the edge set is NOT, the middleware
 * 410s every new city page while the sitemap/pages happily emit them —
 * systematic 410s on valid URLs. This test makes that drift a CI failure.
 */
import { describe, it, expect } from 'vitest';
import { CITIES } from '@/lib/pseo/city-data/cities';
import { CITY_SLUGS, isKnownCitySlug } from '@/lib/pseo/city-data/city-slugs-edge';

describe('CITY_SLUGS edge set ↔ CITIES dataset drift guard', () => {
  it('edge set contains exactly the slugs in CITIES (no missing, no extra)', () => {
    const fromCities = [...new Set(CITIES.map((c) => c.slug))].sort();
    const fromEdge = [...CITY_SLUGS].sort();
    // If this fails: cities.ts and city-slugs-edge.ts were regenerated out of
    // lockstep. Regenerate the edge set (see the header of city-slugs-edge.ts)
    // so middleware never 410s a valid city page or admits a removed one.
    expect(fromEdge).toEqual(fromCities);
  });

  it('every edge slug is already lowercase (isKnownCitySlug lowercases its input)', () => {
    const nonLower = [...CITY_SLUGS].filter((s) => s !== s.toLowerCase());
    expect(nonLower).toEqual([]);
  });

  it('isKnownCitySlug agrees with the dataset for a sample and rejects garbage', () => {
    const sample = CITIES[0];
    expect(sample).toBeDefined();
    expect(isKnownCitySlug(sample.slug)).toBe(true);
    expect(isKnownCitySlug(sample.slug.toUpperCase())).toBe(true);
    expect(isKnownCitySlug('definitely-not-a-city-zz')).toBe(false);
  });
});
